In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [14]:
df.sample(9)

    age  gender  fever   cough       city has_covid
90   59  Female   99.0  Strong      Delhi        No
46   19  Female  101.0    Mild     Mumbai        No
97   20  Female  101.0    Mild  Bangalore        No
25   23    Male    NaN    Mild     Mumbai        No
32   34  Female  101.0  Strong      Delhi       Yes
38   49  Female  101.0    Mild      Delhi       Yes
52   47  Female  100.0  Strong  Bangalore       Yes
37   55    Male  100.0    Mild    Kolkata        No
70   68  Female  101.0  Strong      Delhi        No

In [16]:
df["age"].value_counts()

age
65    4
34    4
19    4
5     3
69    3
42    3
49    3
20    3
64    3
83    3
27    3
51    3
82    3
16    2
60    2
38    2
23    2
24    2
81    2
10    2
80    2
47    2
71    2
73    2
12    2
11    2
25    2
75    2
14    2
56    1
59    1
6     1
46    1
8     1
54    1
48    1
68    1
17    1
26    1
44    1
66    1
18    1
72    1
22    1
50    1
55    1
74    1
15    1
33    1
13    1
40    1
70    1
84    1
31    1
79    1
Name: count, dtype: int64

In [7]:
def missval(column_name):
    return 100 - df[column_name].value_counts().sum()

for i in range(1, 6):
    col_name = df.columns[i-1]  
    missing = missval(col_name)
    print(f"Column '{col_name}': {missing} missing values")

Column 'age': 0 missing values
Column 'gender': 0 missing values
Column 'fever': 10 missing values
Column 'cough': 0 missing values
Column 'city': 0 missing values

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('has_covid',axis=1), df['has_covid'], test_size=0.3)
print(f"x_train size: {x_train.size}, x_test size: {x_test.size}")

x_train size: 350, x_test size: 150

In [9]:
# SimpleImputer for fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.transform(x_test[['fever']])  # Use transform, not fit_transform
print(f"x_train_fever shape: {x_train_fever.shape}")

x_train_fever shape: (70, 1)

In [10]:
# OrdinalEncoder for cough column
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.transform(x_test[['cough']])  # Use transform, not fit_transform
print(f"x_train_cough shape: {x_train_cough.shape}")

x_train_cough shape: (70, 1)

In [11]:
# OneHotEncoder for gender and city columns - FIX: Add sparse_output=False
ohe = OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])  # Use transform, not fit_transform
print(f"x_train_gender_city shape: {x_train_gender_city.shape}")

x_train_gender_city shape: (70, 4)

In [12]:
# Extract age column
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values
print(f"x_train_age shape: {x_train_age.shape}")

x_train_age shape: (70, 1)

In [13]:
# Concatenate all transformed features
x_train_transformed = np.concatenate((x_train_age, x_train_fever, x_train_gender_city, x_train_cough), axis=1)
x_test_transformed = np.concatenate((x_test_age, x_test_fever, x_test_gender_city, x_test_cough), axis=1)

print(f"x_train_transformed shape: {x_train_transformed.shape}")
print(f"x_test_transformed shape: {x_test_transformed.shape}")

x_train_transformed shape: (70, 7)
x_test_transformed shape: (30, 7)

In [17]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [20]:
import searborn as sns

ModuleNotFoundError: No module named 'searborn'